### ISSUE TITLE
Parameters not being mapped

### ISSUE THREAD

**Issue by ChloeDawn** [Chocohead/Fabric-Loom#3]
Recent changes (presumably from pulling in upstream changes) have resulted in parameters no longer being mapped in generated sources. Suspected commit:  https://github.com/Chocohead/fabric-loom/commit/d151bd59ec9e8c958c5c8b88fdd47b1aa394e3df

**Comment by Chocohead** [comment]
The parameter names aren't attached by decompiling but during remapping, as it's the LVT that the names are saved in (hence abstract methods don't get proper names as they don't have an LVT to be saved in). Given I've not touched the Tiny fork or `MapJarsTiny`, and there shouldn't have been any changes to `MappingsProvider`, I suggest double checking you're actually using the `enigma@zip` Enigma mappings. Failing that, knowing the last version that definitely did work will certainly ease the search for what else might be going wrong.

**Comment by ChloeDawn** [comment]
I forgot to restore the `enigma@zip` attribute when reverting to the fork after testing upstream... Dammit.

**Comment by ChloeDawn** [comment]
Just ran `genSourcesDecompile` with the following updated dependency configuration, and still didnt' get mapped parameters in sources, welp.
```gradle
dependencies {
  minecraft "com.mojang:minecraft:$game"
  mappings "net.fabricmc:yarn:$game+$mappings:enigma@zip"
  modCompile "net.fabricmc:fabric-loader:$loader"
  modCompile "net.fabricmc.fabric-api:fabric-api:$api"
  implementation "net.fabricmc:yarn:$game+$mappings"
  implementation "com.google.code.findbugs:jsr305:$findbugs"
  implementation "org.jetbrains:annotations:$annotations"
  implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlin"
}
```
```properties
loom = c6b538f
kotlin = 1.3.31
game = 1.14.3-pre1
mappings = build.1
loader = 0.4.8+build.154
api = 0.3.0+build.175
findbugs = 3.0.2
annotations = 17.0.0
```
Loom revision used: [c6b538f](https://github.com/SleeplessDevelopment/fabric-loom/tree/c6b538f6844dfdc361dc8d52406320231de3312a)

**Comment by Chocohead** [comment]
Does `~/.gradle/caches/fabric-loom/mappings/yarn-params-1.14.3-pre1-1` exist? If it is creating that then it's at least trying, otherwise it must be upset elsewhere.

**Comment by ChloeDawn** [comment]
It does not exist

**Comment by Chocohead** [comment]
Hmmm, given you used the normal mappings before I suspect what's happened is clear (if unobvious without appreciating how `MappingProvider`'s laziness works). If you run `cleanLoomMappings` then `genSources` it will generate then subsequently use the parameter mappings.

The mapping files are only made when the base (pre-Stitch) or normal (post-Stitch) forms are missing. Thus if you've run with the normal mappings before neither of those two files are missing. Of course using Enigma there is also the Intermediary and the parameter mapping files, but as the normal and gz mappings don't require those, there is nothing testing for them to exist as a requirement to regenerate the complete mapping files. Clearing the base mappings along with using the Enigma mappings will proper generate everything it needs no matter the previous runs Loom might have made (including with other versions/forks, albeit doing more work than might be necessary from quite coarse conditions).
