### ISSUE TITLE
[jekan't] Parameter names are missing when using client-only merging

### ISSUE THREAD

**Issue by Juuxel** [Chocohead/Fabric-Loom#4]
This *might* be a problem with the custom obf namespace stuff I do in my fork, but I doubt it.

**Comment by Chocohead** [comment]
I'd be much more suspicious of how `SnappyRemapper` was remapping the jar rather than `MapJarsTiny`. Try catching up to 7c254f1 and see if things are better behaved.

**Comment by Chocohead** [comment]
This should be fixed from fed0efb.
