### ISSUE TITLE
Can't run the game on recent Fabric API versions

### ISSUE THREAD

**Issue by Juuxel** [Chocohead/Fabric-Loom#6]
AWs from dependencies aren't naturally getting remapped, so Loader crashes with `Namespace (intermediary) does not match current runtime namespace (named)`.

**Comment by Chocohead** [comment]
This was fixed back in June, not sure why Github never closed the issue after the push

**Comment by Juuxel** [comment]
The commit isn't on the repo's default branch so GH doesn't close the issue.

**Comment by Chocohead** [comment]
It wasn't at the time, `leaf` was the default branch at the time, but it has been for several months now:

![image](https://user-images.githubusercontent.com/4021725/98059245-88fcb300-1e3e-11eb-92a6-4ba35b27d4a2.png)
